spring:
  application:
    name: hello-service

#server:
#  port: 8080
#management:
#  port: 54001
#  health:
#    mail:
#      enabled: false

info:
  name: "xlbs"
  age: 25
  email: 928135874@qq.com
  blog:
    name: "我的博客"
    address: http://localhost:8080/xlbsblog
    version: 1.0
eureka:
  client:
    service-Url:
      defaultZone: http://localhost:1111/eureka/

